export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const CART_PRODUCTS = 'CART_PRODUCTS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';